name: Vulnerability Scan

on:
  pull_request:
    branches:
      - "*.*"
    types:
      - opened
      - synchronize

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code for this repository
        uses: actions/checkout@v4

      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          scan-type: "repo"
          scan-ref: "./"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
          ignore-unfixed: true
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db